<?php
/**
 * Maps the plugin namespace onto the WordPress file naming convention.
 *
 * @package BlueBranch\Chatbot
 */

namespace BlueBranch\Chatbot;

defined( 'ABSPATH' ) || exit;

/**
 * Turns BlueBranch\Chatbot\Api_Client into includes/class-api-client.php and
 * BlueBranch\Chatbot\Admin\Settings_Page into admin/class-settings-page.php.
 *
 * Written by hand rather than generated by Composer: a plugin that ships a
 * vendor directory only to find its own classes makes every installation
 * carry an autoloader that may collide with another plugin's.
 */
class Autoloader {

	/**
	 * Sub-namespace to directory. Everything else lives in includes/.
	 *
	 * @var array<string, string>
	 */
	private static $directories = array(
		'Admin' => 'admin/',
	);

	/**
	 * Hooks the autoloader into PHP.
	 *
	 * @return void
	 */
	public static function register() {
		spl_autoload_register( array( __CLASS__, 'load' ) );
	}

	/**
	 * Loads one class file if the class belongs to this plugin.
	 *
	 * @param string $class_name Fully qualified class name.
	 * @return void
	 */
	public static function load( $class_name ) {
		$prefix = __NAMESPACE__ . '\\';

		if ( ! str_starts_with( $class_name, $prefix ) ) {
			return;
		}

		$relative  = substr( $class_name, strlen( $prefix ) );
		$directory = 'includes/';
		$parts     = explode( '\\', $relative );

		if ( count( $parts ) > 1 && isset( self::$directories[ $parts[0] ] ) ) {
			$directory = self::$directories[ array_shift( $parts ) ];
		}

		$file = $directory . 'class-' . str_replace( '_', '-', strtolower( implode( '-', $parts ) ) ) . '.php';
		$path = BLUEBRANCH_CHATBOT_DIR . $file;

		if ( is_readable( $path ) ) {
			require_once $path;
		}
	}
}
